name: OWEB Data Intake Questionnaire
description: File a data intake questionnaire for OWEBdb.
title: "[Data Intake]: "
labels: ["documentation"]
assignees: ["jmhatch", "NMucci1"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this data intake questionnaire!
  - type: markdown
    attributes:
      value: |
        # General data description
  - type: textarea
    id: owner
    attributes:
      label: Data owner / manager
      description: Who is the main point of contact for all communication and information related to the data?
      value: |
        Name:
        Title:
        Affiliation:
        Email:
        Phone:
      render: markdown
    validations:
      required: true
  - type: dropdown
    id: project
    attributes:
      label: Project / program
      description: What project or program are the data a part of?
      multiple: false
      options:
        - Survey Mitigation
        - IHA Protected Species Monitoring
      default: 0
    validations:
      required: true
  - type: textarea
    id: location
    attributes:
      label: Data location
      description: Where are data currently stored?
      render: markdown
    validations:
      required: true
  - type: dropdown
    id: data-type
    attributes:
      label: What is the type of data?
      description: Spatial data type for the data intake.
      multiple: false
      options:
        - Shapefile
        - Raster
        - Other (please specify below)
    validations:
      required: true
  - type: input
    id: data-type-other
    attributes:
      label: If Other, please specify data type
      description: If you selected Other from the dropdown menu above, please specify the spatial data type.
      placeholder: ex. Geodatabase (*.gdb)
    validations:
      required: false
  - type: textarea
    id: metadata
    attributes:
      label: Data processing
      description: Where are the data currently stored?
      value: |
        Data processing procedures, code repository for data processing
        Data collection methods
        Frequency of data collection
        How often is data both collected and updated?
        Are we receiving data in a processed and ‘final’ form?
      render: markdown
    validations:
      required: true
