name: OWEB Data Intake Questionnaire
description: File a data intake questionnaire for OWEBdb.
title: "[Data Intake]: "
labels: ["documentation"]
assignees: ["jmhatch", "NMucci1"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this data intake questionnaire!
  - type: markdown
    attributes:
      value: |
        # General data description
  - type: textarea
    id: owner
    attributes:
      label: Data owner / manager
      description: Who is the main point of contact for all communication and information related to the data?
      value: |
        Name:
        Title:
        Affiliation:
        Email:
        Phone:
      render: markdown
    validations:
      required: true
  - type: dropdown
    id: project
    attributes:
      label: Project / program
      description: What project or program are the data a part of?
      multiple: false
      options:
        - Survey Mitigation
        - IHA Protected Species Monitoring
      default: 0
    validations:
      required: true
  - type: input
    id: location
    attributes:
      label: Data location
      description: Where are the data currently stored?
      placeholder: ex. nefscdb1
    validations:
      required: true
  - type: dropdown
    id: data-type
    attributes:
      label: What is the type of data?
      description: Spatial data type.
      multiple: false
      options:
        - Shapefile
        - Raster
        - Other (please specify below)
    validations:
      required: true
  - type: input
    id: data-type-other
    attributes:
      label: If Other, please specify data type
      description: If you selected Other from the dropdown menu above, please specify the spatial data type.
      placeholder: ex. Geodatabase (*.gdb)
    validations:
      required: false
  - type: textarea
    id: metadata
    attributes:
      label: Metadata
      description: Are we receiving raw data or data in a processed and 'final' form?
      value: |
        Data processing procedures or a code repository for data processing
        Data collection methods
        Frequency of data collection
          - How often is data both collected and updated?
        Where is metadata currently stored?
        Process for producing and maintaining metadata
      render: markdown
    validations:
      required: true
  - type: dropdown
    id: non-spatial
    attributes:
      label: Any data attributes that are non-spatial (e.g., stratum id)?
      description: Non-satial data attributes.
      multiple: false
      options:
        - Yes
        - No
    validations:
      required: true
  - type: text
    id: non-spatial-desc
    attributes:
      label: If you selected Yes above, please explain
    validations:
      required: false
  - type: checkboxes
    id: spatial
    attributes:
      label: Spatial Information
      description: What spatial metadata are included?
      options:
        - label: Spatial reference / coordinate system
        - label: Geographic extent
        - label: Measurement system (meters, feet, etc)
        - label: Data resolution
  - type: markdown
    attributes:
      value: |
        # Background information
  - type: textarea
    id: background
    attributes:
      label: General description of project purpose and summary
      description: Provide any links to related websites/background information.
      value: |
        To attach files,
          1) Open a blank issue after submitting the Data Intake Questionnaire.
          2) Attach files to the description section of the new blank issue.
          3) Reference the number of the submitted Data Intake Questionnaire in the title or description of the new blank issue.
          4) Submit the new blank issue (don't forget an informative title).
        For example,
          "Attaching report files as pdfs. Addresses PEMAD-OWEB-Data_Dictionary#1."
          In the example above, #1 is the number assigned to the corresponding Data Intake Questionnaire.
      render: markdown
    validations:
      required: false
