name: OWEB Data Intake Questionnaire
description: File a data intake questionnaire for OWEBdb.
title: "[Data Intake]: "
labels: ["documentation"]
assignees: ["jmhatch", "NMucci1"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this data intake questionnaire!
  - type: markdown
    attributes:
      value: |
        # General data description
  - type: textarea
    id: owner
    attributes:
      label: Data owner / manager
      description: |
        Add description
      value: |
        Name:
        Title:
        Affiliation:
        Email:
        Phone:
      render: markdown
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Project / program
      description: What project or program is this data a part of?
      options:
        - Survey Mitigation
        - IHA Protected Species Monitoring
      default: 0
    validations:
      required: true
