## Standard Operating Procedure

### Naming convention for spatial tables in oracle database

NEFSC scientific survey strata are compiled in the oracle database under the MDEB_SPATIAL schema. All spatial tables are projected in North American Datum of 1983 (NAD 83). NEFSC scientific survey strata naming conventions are as follows:

|       *SCHEMA.PROJECTABBR_SURVEYCODE_STRATA*
| 
| For example, the Bottom Trawl Survey strata:
|       *MDEB_SPATIAL.SMIT_BTS_STRATA*
| 
| Surveys with associated substrata are named as follows:
|       *SCHEMA.SMIT_SURVEYCODE_SUBSTRATA*
| 
| Surveys with associated historical strata are named as follows:
|       *SCHEMA.SMIT_SURVEYCODE_STRATA_HISTORIC*
| 
| Surveys with an associated point layer (ex. sample stations) are named as follows:
|       *SCHEMA.SMIT_SURVEYCODE_STATIONS*
| 
| Surveys with an associated line layer (ex. surveylines) are named as follows:
|       *SCHEMA.SMIT_SURVEYCODE_LINES*
| 
| There are three tables containing metadata for the associated survey strata. They are named as follows:
|       *SCHEMA.SMIT_FEATURES* contains information about survey strata feature services.
|       *SCHEMA.SMIT_FIELDS* contains information about fields, including aliases and fields descriptions.
|       *SCHEMA.SMIT_LAYERS* contains information about layers within feature services.

### Table 1. NEFSC Scientific Survey names and survey codes

| **Survey code** | **Survey name**                                              |
|---------------------|---------------------------------------------------|
| BTS             | Bottom Trawl Survey                                          |
| COASTSPAN       | Cooperative Atlantic States Shark Pupping and Nursery Survey |
| CSBLL           | Coastal Shark Bottom Longline Survey                         |
| ECOMON          | Ecosystem Monitoring Survey                                  |
| EDNA            | eDNA Survey                                                  |
| GOMBLL          | Gulf of Maine Bottom Longline Survey                         |
| HL              | Hook and Line Survey                                         |
| MMST            | Marine Mammal and Sea Turtle Survey                          |
| NARW            | North Atlantic Right Whale Aerial Survey                     |
| OQ              | Ocean Quahog Survey                                          |
| SC              | Atlantic Surfclam Survey                                     |
| SCALLOP         | Sea Scallop Survey                                           |
| SEAL            | Seal Aerial Survey                                           |
| SHRIMP          | Northern Shrimp Survey                                       |
| TURTLE          | Turtle Ecology Survey                                        |
